### ISSUE TITLE
add more babershop plse

### ISSUE THREAD

**Issue by kheire007** [CCasusensa/barbershop#1]
{x = -814.308,  y = -183.823,  z = 36.568},
  --{x = 136.826,   y = -1708.373, z = 28.291}, this one is donne
  {x = -1282.604, y = -1116.757, z = 5.990},
  {x = 1931.513,  y = 3729.671,  z = 31.844},
  {x = 1212.840,  y = -472.921,  z = 65.208},
  {x = -32.885,   y = -152.319,  z = 56.076},
  {x = -278.077,  y = 6228.463,  z = 30.695},

**Comment by apostoloskotsiras** [comment]
im working on it to add all the barbershops and the CCasusensa will upload it here 
best regards from our team :)

**Comment by apostoloskotsiras** [comment]
we have the full version with all the barbershops and we sell it send us message on discord
αμπουσερούκος καπιταλουκος#1924
lrenex#0001
here is an invite link: https://discord.gg/S22GN36
