### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by xaxathebest** [CCasusensa/barbershop#2]
Hi CCasusensa

sorry for writing here, but I didn't know how to contact you.
I am looking for a Pangya S4.9 client for local server like the one you are mentioning here:

http://forum.ragezone.com/f971/pangya-server-pangya-season-4-a-1044054/#post8333678

Unfortunately the one you uploaded is no longer available.

Could you please send it to me at: xaxathebest@gmail.com ?

Thanks a lot.

**Comment by CCasusensa** [comment]
Sorry i no longer have a file

**Comment by xaxathebest** [comment]
:(
Do you know where I can get it, or can you help me getting it working ?

Il giorno mar 10 mar 2020 alle ore 18:19 Kinesis <notifications@github.com>
ha scritto:
